### ISSUE TITLE
Proposal Governance

### ISSUE THREAD

**Issue by ddymko** [Porthorian/overengineered-eats#4]
We need a Governance board to make sure this is a community driven org

---

Open Source Software Project Governance Document

1. Introduction

    Project Name: [Project Name]
    Mission: Briefly describe the purpose and goals of the open-source project.
    License: Specify the open-source license under which the project is released (e.g., MIT, Apache 2.0).

2. Project Governance Structure

    Maintainers: List the project maintainers, their roles, and responsibilities.
    Contributors: Define the process for becoming a contributor and participating in the project.
    Community: Highlight the importance of an open and inclusive community for the project's success.

3. Decision-Making Process

    Quorum Definition: Define the minimum number of maintainers required to reach a decision (quorum). For example, quorum might be defined as 2 out of 3 maintainers.
    Decision Types: Differentiate between day-to-day technical decisions and major project direction decisions.
    Consensus Model: Describe the process for reaching consensus among maintainers for major decisions. This might include discussions, voting, and reaching a decision within the quorum.

4. Contribution Guidelines

    Code of Conduct: Reference or include a link to the project's code of conduct that outlines expected behavior for all community members.
    Contributing: Provide a guide for new contributors on how to submit code, report issues, and engage in discussions.

5. Code Review Process

    Pull Requests: Detail the process for submitting and reviewing pull requests.
    Reviewers: Specify who can review and approve pull requests.
    Criteria: Define the criteria for code quality, testing, documentation, and adherence to coding standards.

6. Release Management

    Versioning: Explain how the project handles versioning and release numbering.
    Release Process: Outline the steps to prepare and publish releases.
    Changelog: Describe how release notes and changelogs are maintained.

7. Issue Tracking and Bug Reporting

    Issue Tracker: Specify the platform used for issue tracking (e.g., GitHub Issues) and guidelines for submitting bug reports or feature requests.
    Triaging: Detail how issues are categorized, prioritized, and assigned.

8. Roadmap and Project Direction

    Project Vision: Describe the overall vision and goals for the project's future.
    Roadmap: Outline planned features, enhancements, and milestones.
    Feedback: Explain how community feedback is considered when shaping the project's direction.

9. Community Engagement

    Communication Channels: List official communication channels, such as mailing lists, forums, chat rooms, and social media.
    Events: Highlight any community events, meetings, or conferences related to the project.

10. Governance Review and Updates

    Review Periodicity: Specify how often the governance document will be reviewed and updated.
    Community Input: Encourage the community to provide input and feedback on governance improvements.

11. License and Copyright

    License Notice: Include the full text of the chosen open-source license.
    Copyright Notice: Specify the project's copyright holders and contributors.

12. Acknowledgments

    Recognize individuals or organizations that have significantly contributed to the project.

Appendix: Code of Conduct

    Attach the project's code of conduct outlining expected behavior and guidelines for interactions within the community.

**Comment by aanthonyrizzo** [comment]
I have to agree with you here @ddymko. Its very important that ensure that proper controls and standard practices are established and then enforced.

**Comment by Porthorian** [comment]
Added in [dc915e8](https://github.com/Porthorian/overengineered-eats/commit/dc915e8f0a62c7dd3a457d8d5245919130c7b907)
